lexik_jwt_authentication:
    secret_key: '%env(JWT_SECRET_KEY)%' # La clé secrète pour signer les tokens JWT
    public_key: '%env(JWT_PUBLIC_KEY)%' # Optionnel, si tu utilises une clé publique pour vérifier les tokens
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600 # Durée de vie du token en secondes
