nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['*']
        allow_headers: ['Content-Type', 'Authorization'] 
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE'] 
        max_age: 3600
    paths:
        '^/': # Default rules for other routes
            allow_origin: ['*']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE']            
            max_age: 3600