security:
    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        users_in_memory: { memory: null }
        users_in_database:
            entity:
                class: App\Entity\User
                property: pseudo

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/login
            stateless: true
            provider: users_in_database
            security: false
            # entity:
            #     class: App\Entity\User
            #     property: apiToken

        api:
            pattern: ^/api
            stateless: true
            provider: users_in_database
            guard:
                authenticators:
                    - App\Security\ApiAuthenticator

    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/hello, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
