security:
    encoders:
        App\Entity\Joueur:
            algorithm: auto
        App\Entity\Admin:
            algorithm: auto
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Joueur
                property: email
        admin_provider:
            entity:
                class: App\Entity\Admin
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login_api:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\JoueurAuthenticator

        login_intranet:
            pattern:  ^/intranet/login
            stateless: true
            anonymous: true
            provider: admin_provider
            guard:
                authenticators:
                    - App\Security\AdminAuthenticator

        intranet_register:
            pattern: ^/intranet/register
            security: false
        
        api_register:
            pattern: ^/api/register
            security: false
            
        api_parametres:
            pattern: ^/api/parametres
            security: false

        # Intranet firewall must come before the API firewall to ensure priority
        intranet:
            pattern: ^/intranet/
            stateless: true
            provider: admin_provider
            guard:
                authenticators:
                    - App\Security\AdminJWTAuthenticator

        api:
            pattern:   ^/api
            stateless: true
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\JoueurJWTAuthenticator

    access_control:
        - { path: ^/api/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/parametres, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/intranet/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/intranet/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/intranet/, roles: ROLE_ADMIN }
        - { path: ^/api, roles: ROLE_USER }